### ISSUE TITLE
!emojiRain

### ISSUE THREAD

**Issue by onewheelskyward** [onewheelskyward/lita-onewheel-forecast-io#25]
@agjohnson's idea (much like the original boxes)

**Comment by onewheelskyward** [comment]
[15:18:26]  [lampd1]	💦 🌧  🏊‍♂️
[15:18:58]  [lampd1]	🌊⛲💧〰️🐳

**Comment by agjohnson** [comment]
On weechat, iterm, osx:

![image](https://user-images.githubusercontent.com/1140183/30671033-2c78532c-9e22-11e7-9cac-155d63e1c7de.png)

**Comment by onewheelskyward** [comment]
Annnnnd done.
